### ISSUE TITLE
GMAT 2020a build error

### ISSUE THREAD

**Issue by schadegg-astro** [JuliaSpace/GMAT.jl#4]
Documenting for documenting's sake.
deps/build.jl currently fails for GMAT2020a (macosx-x64): 

`/GMAT.jl/deps/GMAT/R2020a/bin/navigation.jar -> ../bin/GMAT-R2020a_Beta.app/Contents/Frameworks/navigation.jar
ERROR: LoadError: Provider Binaries failed to satisfy dependency libCInterface. Maybe you forgot to declare an alias in a library_dependency?`

**Comment by helgee** [comment]
The 2020a release has a new API thus `libCinterface` does not exist anymore.

The bigger problem is that we would need to build GMAT via BinaryBuilder.jl to make it work with the new Julia package infrastructure.

~~@giordano How hard would it be to build a GUI toolkit like wxWidgets with BinaryBuilder?~~

Scratch that the new version can be built without the GUI 🎉
